import { Geist, Geist_Mono, Space_Grotesk } from "next/font/google";
import "./globals.css";
import RouteLoader from "./Components/RouteLoader";
import { ThemeProvider } from "./Components/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const SpaceGrotesk = Space_Grotesk({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})
export const metadata = {
  title: "Be Smart with BitSmart Tech",
  description: "Generated by create next app",

};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body

        className={`${geistSans.variable} ${geistMono.variable}  antialiased overflow-x-hidden`}
      >
        <ThemeProvider>
          <RouteLoader />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
